# Generated by Django 2.2.20 on 2022-11-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель продукта')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100, verbose_name='Название страны')),
                ('city', models.CharField(max_length=100, verbose_name='Название города')),
                ('street', models.CharField(max_length=100, verbose_name='Название улицы')),
                ('house_number', models.CharField(max_length=50, verbose_name='Номер дома')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='сompanies', to='companies.Product')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company')),
            ],
        ),
    ]
