# Generated by Django 4.1.3 on 2022-11-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_product_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hierarchy',
            field=models.SmallIntegerField(choices=[(0, 'Factory'), (1, 'Distributor'), (2, 'Dealership'), (3, 'Large retail network'), (4, 'Individual entrepreneur')], default=1),
            preserve_default=False,
        ),
    ]
